application: REPLACE-WITH-YOUR-APP-ID
env_variables:
  AGILE_KEYCHAIN_ARCHIVE: 'REPLACE-WITH-ZIPPED-FILENAME'
  USER_EMAIL: 'REPLACE-WITH-EMAIL-LINKED-TO-A-GOOGLE-ACCOUNT'

## You should not need to change anything below this line ##

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: ae1pass.app
  login: required
  secure: always
